name: flask-app

on:
  push:
    branches:
      - github-actions

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Lint with flake8
#        run: flake8 .

      - name: Test with pytest
        run: pytest tests.py

  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "actions-flask"
          heroku_email: "kuchevwork@yandex.ru"
          usedocker: true
